### ISSUE TITLE
Bad translated output for attribute((transparent_union))

### ISSUE THREAD

**Issue by PHHargrove** [Intrepid/upc2c#113]
Given the following input:
```C
typedef union {
    int *p;
    uintptr_t u;
} foo_t __attribute__((transparent_union));
```

The upc2c translator is emitting the following:
```C
typedef union __attribute__((transparent_union)) {
    int *p;
    uintptr_t u;
} foo_t;
```

Notice that the attribute has changed location.
The clang C compiler (including, but not limited to, one built from the same sources as the translator) is happy with the original form, but rejects the translated code:
```
$ clang -c foo.c
foo.c:3:30: warning: transparent_union attribute can only be applied to a union definition; attribute ignored
      [-Wignored-attributes]
typedef union __attribute__((transparent_union)) {
                             ^
1 warning generated.
```

While this is only a warning, it means that code that requires the transparent_union property of the union may encounter additional warnings or errors.

This did not occur prior to the recent 3.6 merge.

**Comment by swatanabe** [comment]
AMDG

  I think this is a clang bug.  gcc accepts it
and the gcc documentation seems quite clear
that this placement of the attribute is
correct.

https://gcc.gnu.org/onlinedocs/gcc-5.2.0/gcc/Type-Attributes.html

          typedef union __attribute__ ((__transparent_union__))
            {
              int *__ip;
              union wait *__up;
            } wait_status_ptr_t;

          pid_t wait (wait_status_ptr_t);

In Christ,
Steven Watanabe

**Comment by nenadv** [comment]
Can you check if there is an upstream fix that we can use?

**Comment by swatanabe** [comment]
AMDG

On 10/06/2015 11:12 AM, Nenad Vukicevic wrote:
> Can you check if there is an upstream fix that we can use?
> 

  This needs to be changed in DeclPrinter,
unless we don't care about compatibility
with the official clang 3.6 release.

In Christ,
Steven Watanabe

**Comment by nenadv** [comment]
I would fix it if possible.

And if that was fixed in 3.7 we should probable merge once 3.7.1 comes out.

**Comment by swatanabe** [comment]
AMDG

On 10/06/2015 12:25 PM, Nenad Vukicevic wrote:
> I would fix it if possible.
> 

  Fixing parsing of the attribute appears non-trivial.
The problem is essentially that the code for handling
the transparent_union attribute requires the union to
be complete and attributes are processed when they appear,
which before the union body in this case.
  It's a lot easier to change DeclPrinter to put
__attribute__((transparent_union)) after the body, which
we need to do anyway, if we want clang-upc2c to work
with a system clang.  I'm testing a workaround now.

> And if that was fixed in 3.7 we should probable merge once 3.7.1 comes out.
> 

Sure.

In Christ,
Steven Watanabe

**Comment by PHHargrove** [comment]
>  It's a lot easier to change DeclPrinter to put __attribute__((transparent_union)) after the body, which
we need to do anyway, if we want clang-upc2c to work with a system clang.

I agree w/ Steven that we want the fix in DeclPrint so that the system Clang will accept the clang-upc2c output.  I think that we should retain that fix even if we eventually merge in a fix that parses the current output correctly.

-Paul

**Comment by PHHargrove** [comment]
Steven's fix (7fe05a) went in last night and I am retesting most of the platforms where the problem manifested.  The first partial result is in, and confirms the problem is fixed.

I doubt the other platforms will behave differently, or that the fix will lead to regression on other test cases.  However, I am waiting for the remainder of the results before I can rest easy.

**Comment by PHHargrove** [comment]
All looks good in my testing.
