### ISSUE TITLE
cupc2c on MacOS X

### ISSUE THREAD

**Issue by robegan21** [Intrepid/upc2c#118]
Hello,

I'm having trouble with the install on MacOS X Mojave 10.14.  Specifically it looks like the standard libraries can not be found.

Robs-Mac-mini:hipmeraculous regan$ CC=cc CXX=c++ /Users/regan/install/bin/clang-upc2c -v test/hipmer/hello_world.upc 
clang version 3.9.1  (UPC 3.9.1-0 20170320) 
Target: x86_64-apple-darwin18.0.0
Thread model: posix
InstalledDir: /Users/regan/install/bin
clang Invocation:
 "/Users/regan/install/bin/clang-upc2c" "-cc1" "-triple" "x86_64-apple-macosx10.14.0" "-Wdeprecated-objc-isa-usage" "-Werror=deprecated-objc-isa-usage" "-fsyntax-only" "-disable-free" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "hello_world.upc" "-mrelocation-model" "pic" "-pic-level" "2" "-mthread-model" "posix" "-mdisable-fp-elim" "-masm-verbose" "-munwind-tables" "-target-cpu" "core2" "-target-linker-version" "409.12" "-v" "-dwarf-column-info" "-debugger-tuning=lldb" "-resource-dir" "/Users/regan/install/bin/../lib/clang/3.9.1" "-fdebug-compilation-dir" "/Users/regan/workspace/hipmeraculous" "-ferror-limit" "19" "-fmessage-length" "186" "-stack-protector" "1" "-fblocks" "-fobjc-runtime=macosx-10.14.0" "-fencode-extended-block-signature" "-fmax-type-align=16" "-fdiagnostics-show-option" "-x" "upc" "test/hipmer/hello_world.upc"

clang -cc1 version 3.9.1 based upon LLVM 3.9.1 default target x86_64-apple-darwin18.0.0
ignoring nonexistent directory "/usr/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /Users/regan/install/bin/../lib/clang/3.9.1/include
 /System/Library/Frameworks (framework directory)
 /Library/Frameworks (framework directory)
End of search list.
test/hipmer/hello_world.upc:1:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^
1 error generated.

Here are all the possible versions of stdio.h on my system:

Robs-Mac-mini:hipmeraculous regan$ find / -type f -name 'stdio.h' 2>/dev/null
/usr/local/Cellar/gcc/8.2.0/include/c++/8.2.0/tr1/stdio.h
/usr/local/Cellar/gcc/8.2.0/lib/gcc/8/gcc/x86_64-apple-darwin18.0.0/8.2.0/include/ssp/stdio.h
/usr/local/Cellar/gcc/8.2.0/lib/gcc/8/gcc/x86_64-apple-darwin18.0.0/8.2.0/include-fixed/stdio.h
/Library/Developer/CommandLineTools/usr/include/c++/v1/stdio.h
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/stdio.h
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/sys/stdio.h
/private/var/folders/7f/7vbml7jx15z88yhv_b19bxlh0000gn/T/bupc-regan-hipmer-builds/build-bupc/dbg/upcr_geninclude/stdio.h
/private/var/folders/7f/7vbml7jx15z88yhv_b19bxlh0000gn/T/bupc-regan-hipmer-builds/build-bupc/opt_cupc2c/upcr_geninclude/stdio.h
/private/var/folders/7f/7vbml7jx15z88yhv_b19bxlh0000gn/T/bupc-regan-hipmer-builds/build-bupc/opt/upcr_geninclude/stdio.h
/private/var/folders/7f/7vbml7jx15z88yhv_b19bxlh0000gn/T/bupc-regan-hipmer-builds/build-bupc/dbg_cupc2c/upcr_geninclude/stdio.h
/Users/regan/install/dbg/include/upcr_geninclude/stdio.h
/Users/regan/install/opt/include/upcr_geninclude/stdio.h
/Users/regan/clang-upc-3.9.1-0/tools/clang/test/CodeGen/Inputs/stdio.h
/Users/regan/clang-upc-3.9.1-0/tools/clang/test/Modules/Inputs/crash-recovery/usr/include/stdio.h
/Users/regan/clang-upc-3.9.1-0/tools/clang/test/Modules/Inputs/System/usr/include/stdio.h
/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS.sdk/usr/include/sys/stdio.h
/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS.sdk/usr/include/stdio.h
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/sys/stdio.h
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/stdio.h
/Applications/Xcode.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS.sdk/usr/include/sys/stdio.h
/Applications/Xcode.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS.sdk/usr/include/stdio.h
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/stdio.h
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdio.h
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/sys/stdio.h
/Applications/Xcode.app/Contents/Developer/Platforms/WatchSimulator.platform/Developer/SDKs/WatchSimulator.sdk/usr/include/sys/stdio.h
/Applications/Xcode.app/Contents/Developer/Platforms/WatchSimulator.platform/Developer/SDKs/WatchSimulator.sdk/usr/include/stdio.h
/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator.sdk/usr/include/sys/stdio.h
/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator.sdk/usr/include/stdio.h
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/sys/stdio.h
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/stdio.h
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/stdio.h

I configured and built clang-upc2c following the instructions, which worked fine:

CC=cc CXX=c++ cmake $codedir/$CUPCDIR -DCMAKE_INSTALL_PREFIX:PATH=$installdir -DLLVM_TARGETS_TO_BUILD:=host -DCMAKE_BUILD_TYPE:=Release

**Comment by PHHargrove** [comment]
@robegan21 ,

Xcode 10 (not Mojave specifically) no longer has a `/usr/include`.  To resolve this requires one additional argument to the `cmake` command when preparing to clang-upc2c
Please see [Berkeley UPC Bug 3798](https://upc-bugs.lbl.gov/bugzilla/show_bug.cgi?id=3798)

-Paul

**Comment by robegan21** [comment]
Thanks Paul!  Sorry I didn't see the issue was covered in the Berkeley UPC issues already.  That did the trick!
