### ISSUE TITLE
Incorrect sizes for PTS on ILP32 with -fupc-pts=struct

### ISSUE THREAD

**Issue by PHHargrove** [Intrepid/upc2c#78]
This is the fourth child of issue #74.
It is possible this issue is entirely in clang-upc, rather than upc2c.
It is also possible that the best/only fix belongs in UPCR.

When using the struct PTS, UPCR's phased and phaseless pointer-to-shared are:
````
    typedef struct shared_ptr_struct {
        uintptr_t   s_addr;
        uint32_t    s_thread;
        uint32_t    s_phase;
    } upcr_shared_ptr_t;

      typedef struct pshared_ptr_struct {
          uintptr_t s_addr;
          uint32_t  s_thread;
      } upcr_pshared_ptr_t;
````

For a typical LP64 platform these both take 16 bytes since uintptr_t is 8-bytes long and requires 8-byte alignment.  However, for ILP32 uintptr_t has 4-byte size and alignment, and thus sizeof(upcr_shared_ptr_t) == 12 and sizeof(upcr_pshared_ptr_t) == 8.  However, as shown by the test code and output below, shared arrays of these type get 16-bytes.  Examining more complex examples you will find that Gets and Puts of shared instances of both pts types also *transfer* 16-bytes, resulting in overwritting of neighboring variables and generally bad runtime behavior results.

````
$ cat bug.upc 
#include <upc.h>
#include <stdio.h>
shared [1] int * shared [] x[2];
shared [2] int * shared [] y[2];
int main(void)
{
    printf("C: sizeof(shared [1] int *) = %zd\n",
           sizeof(shared [1] int *));
    printf("C: sizeof(shared [2] int *) = %zd\n",
           sizeof(shared [2] int *));
    printf("UPC: addr(x+1) - addr(x) = %zd\n",
           upc_addrfield(x+1) - upc_addrfield(x));
    printf("UPC: addr(y+1) - addr(y) = %zd\n",
           upc_addrfield(y+1) - upc_addrfield(y));
    return 0;
}
$ ./upcc bug.upc
$ ./upcrun -q -n1 ./a.out
C: sizeof(shared [1] int *) = 8
C: sizeof(shared [2] int *) = 12
UPC: addr(x+1) - addr(x) = 16
UPC: addr(y+1) - addr(y) = 16
````

**Comment by PHHargrove** [comment]
This problem with -fupc-pts=struct seems to exist in a slightly different form on PPC64.
With "-m32" I see such failures as the following extracted from bug509.upc:
```
translator_sz1 sizeof(Grid)=28
translator_sz2 sizeof(Grid)=32
translator_sz3 sizeof(Grid)=32
translator_sz4 sizeof(Grid)=28
bug509.upc:97: int user_main(int, char **): Assertion `translator_sz1 == translator_sz2' failed.
```
Where the two non-equal values are computed by the following (intentional convoluted) code
```
        int one = 1, zero = 0;

        int translator_sz1 = sizeof(Grid);

        char *tp_one = (char*)&(G_amr[0].grids[one]);
        char *tp_zero = (char*)&(G_amr[0].grids[zero]);
        int translator_sz2 = tp_one - tp_zero;
```

In short the `sz1` is `sizeof()` applied to a struct containing a pointer-to-shared, while the `sz2` is the size computed by taking the difference between the addresses of elements 1 and 0 in an array of the same structure type.  Those should, of course, be the same.

The values printed suggest that the `sizeof()` calculation assumes a 4-byte alignment while the array has been built assuming 8-byte alignment.  Note that the ILP32 ABI for this arch has 4-byte alignment for `void*`, but 8-byte alignment for `uint64_t`.

I believe I see at least one place in the clang-upc code where the `uint64_t` alignment is being applied independent of which pts representation is in use, but I still need to test that out.

**Comment by PHHargrove** [comment]
The change I expected to fix the problem did so.
A complete Berkeley test harnness run confirms correct results with both PTS representations.

The pull request is in the clang-upc repo: https://github.com/Intrepid/clang-upc/pull/80
I am fairly certain it is correct, but would appreciate review (or I would have pushed to master).

**Comment by swatanabe** [comment]
AMDG

On 06/09/2015 12:36 PM, Paul H. Hargrove wrote:
> The change I expected to fix the problem did so.
> A complete Berkeley test harnness run confirms correct results with both PTS representations.
> 
> The pull request is in the clang-upc repo: https://github.com/Intrepid/clang-upc/pull/80
> I am fairly certain it is correct, but would appreciate review (or I would have pushed to master).
> 

It looks fine.

In Christ,
Steven Watanabe

**Comment by PHHargrove** [comment]
My pull request has been merged to master with minor change to commit message.
