### ISSUE TITLE
Incorrect translation of integer types with __attribute__ ((__mode__ (__DI__)))

### ISSUE THREAD

**Issue by nenadv** [Intrepid/upc2c#93]
The following example illustrates the code causes an assertion error inside UPCR as ".._val" functions is being called with the size greater then the pointer size:
```
typedef int xint64_t __attribute__ ((__mode__ (__DI__)));
typedef long long yint64_t;

xint64_t oldval;
yint64_t yoldval;

void
set_val (shared void * restrict target)
{
  oldval = *(shared xint64_t *)target;
  yoldval = *(shared yint64_t *)target;
}
```
The following has been produced which shows the usage of "_val" function for 8 bytes quantities on 32 bit machine:
```
void set_val(upcr_shared_ptr_t target) {
    UPCR_BEGIN_FUNCTION();
    yint64_t _bupc_spilld0;
#line 9 "t.upc"
    {
#line 10 "t.upc"
        oldval = ((xint64_t)upcr_get_shared_val(target, 0U, 8U));
#line 11 "t.upc"
        yoldval = (upcr_get_shared(&_bupc_spilld0, target, 0U, 8U) , _bupc_spilld0);
    }
    UPCR_EXIT_FUNCTION();
}
```
Note that this happens only with __attribute__ ((__mode__ (__DI__))), which makes the access of 64 bits.

This code in Transform.cpp is responsible:
```
 766       QualType ResultType = TransformType(Ty).getUnqualifiedType();
 767       if(typeFitsUPCRValuePutGet(ResultType)) {
 768         // Case 1.  Get by value, with type cast if necesssary
```
For the offending type, Ty has size of 64 bits, while ResultType is only 32, which makes typeFitsUPCRValuePutGet() to return TRUE, and access for 8 bytes is being generated with ".._val" UPCR function.

**Comment by PHHargrove** [comment]
This problem is still present in the nightly tests _when using pthreads_.
See, for instance https://upc-bugs.lbl.gov/~phargrov/upc_tests/detail.php?testname=UPC-Atomic-RefImp/atomic_test&date=2015-01-03&config=pcp-j_cupc2c_32_pthr&branch=CUPC2C

**Comment by PHHargrove** [comment]
Previous comment implied the problem was pthreads-specific.
That was a mistake.

See the following for the same failure on a configuration without pthreads: https://upc-bugs.lbl.gov/~phargrov/upc_tests/detail.php?testname=UPC-Atomic-RefImp/atomic_test&date=2014-12-30&config=pcp-j_cupc2c_32&branch=CUPC2C#runfail-pcp-j_cupc2c_32-dbg

**Comment by swatanabe** [comment]
AMDG

On 01/03/2015 03:01 PM, Paul H. Hargrove wrote:
> Previous comment implied the problem was pthreads-specific.
> That was a mistake.
> 
> See the following for the same failure on a configuration without pthreads: https://upc-bugs.lbl.gov/~phargrov/upc_tests/detail.php?testname=UPC-Atomic-RefImp/atomic_test&date=2014-12-30&config=pcp-j_cupc2c_32&branch=CUPC2C#runfail-pcp-j_cupc2c_32-dbg
> 

I've found the problem.  The mode is being passed
through now, but there's an additional flag in
TypedefDecl which needs to be set.  Otherwise the
mode is ignored.

In Christ,
Steven Watanabe

**Comment by PHHargrove** [comment]
Fix appears confirmed by Berkeley's nightly testers.
All known failures attributed to this issue appear to have been eliminated.
-Paul
